name: Deploy to HostGator

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build project
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: |
          npm install
          npm run build

      - name: Deploy client build via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/  # Client static build
          server-dir: /public_html/  # Static site root
          protocol: ftps
          port: 21

      - name: Setup Node.js for server
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install server dependencies
        working-directory: ./server
        run: npm ci
        
      - name: Deploy server to Railway
        uses: railwayapp/railway-deploy-action@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_API_KEY }}
          projectId: ${{ secrets.RAILWAY_PROJECT_ID }}


