name: Deploy to HostGator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build

      - name: Deploy to HostGator via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.5.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build  
          server-dir: /public_html  
          method: ftp  
